name: superdeck_core
description: A core library for SuperDeck.
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck


environment:
  sdk: ">=3.3.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  dart_mappable: ^4.2.2
  yaml: ^3.1.2
  collection: ^1.18.0
  path: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  build_verify: ^3.1.0
